In [1]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([1,2,3,4,5,6],shape=[2,3])
product=tf.matmul(a,b)
print(product)


Tensor("MatMul:0", shape=(3, 3), dtype=int32)


In [2]:
sess=tf.Session()
result=sess.run(product)
print(result)
sess.close()
print(type(result))
print(type(a))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [30]:
# 不需要sess.close()
#两次shilft+Tab显示函数详细内容
with tf.Session() as sess:
    result=sess.run(product)
    print(result)
    

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
<class 'numpy.ndarray'>


In [9]:
#shape中第一位为维度
import numpy as np
c=tf.constant(np.arange(1, 13, dtype=np.int32),shape=[2, 2, 3])
with tf.Session() as sess:
    print(c.eval())
    print(type(c))
#查看具体值

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'tensorflow.python.framework.ops.Tensor'>


In [33]:
#对于变量初始化
x=tf.Variable([1,2],dtype=np.float32)
y=tf.constant([2,3],dtype=np.float32)
sub=tf.subtract(x,y)
add=tf.add(x,y)
#
ini=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(ini)
    print(sess.run(sub))
    print(sess.run(add))
    print(type(x))

[-1. -1.]
[3. 5.]
<class 'tensorflow.python.ops.variables.RefVariable'>


In [2]:
#tf.Variable 使用
import tensorflow as tf
v1=tf.Variable(tf.random_normal(shape=[4,3],mean=0,stddev=1),name='v1')
v2=tf.Variable(tf.constant(2),name='v2')
v3=tf.Variable(tf.ones([4,3]),name='v3')
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v1))
    print(sess.run(v2))
    print(sess.run(v3))


[[ 0.35776946  1.8351156   1.2468109 ]
 [ 1.9221691   1.4659487   0.70206773]
 [-0.07245645  0.88087666  0.59576523]
 [-1.1073397   0.8116849  -1.2475715 ]]
2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
state=tf.Variable(0,name='as_you_like')
#创建一个op，使state加1
new_value=tf.add(state,1)
#赋值op
update=tf.assign(state,new_value)
#变量初始化
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(state))
    for i in range(5):
        sess.run(update)
        print(state.eval())
    print(type(state))

0
1
2
3
4
5
<class 'tensorflow.python.ops.variables.RefVariable'>


In [36]:
input1=tf.constant(np.arange(1,7, dtype=np.int32),shape=[2, 3])
input2=tf.constant(np.arange(1,7, dtype=np.int32),shape=[2, 3])
input3=tf.constant(np.arange(1,7, dtype=np.int32),shape=[3, 2])
with tf.Session() as sess:
    mul=tf.multiply(input1,input2)
    mat=tf.matmul(input2,input3)
    result1=sess.run(mul)
    result2=sess.run(mat)
    print(result1)
    print(result2)
    print(type(input1))
    print(type(mul),'\n',type(result1))

[[ 1  4  9]
 [16 25 36]]
[[22 28]
 [49 64]]
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'> 
 <class 'numpy.ndarray'>


In [41]:
#fetch 同时执行多个opreation
input1=tf.constant(1.0)
input2=tf.constant(3.0)
input3=tf.constant(5.0)
add=tf.add(input3,input2)
mul=tf.multiply(input1,add)
with tf.Session() as sess:
    result=sess.run(mul)
    print(result)
    print(type(result))

8.0
<class 'numpy.float32'>


In [7]:
#feed 将数据以字典形式传入
input1=tf.placeholder(tf.float32)
input2=tf.placeholder(tf.float32)
output=tf.multiply(input1,input2)
with tf.Session() as sess:
    print(sess.run(output,feed_dict={input1:[1.],input2:[2.]}))

[2.]


In [15]:
#一个例子
x_data=np.random.rand(100)
y_data=x_data*0.2+1.45
#构造线性模型
k=tf.Variable(0.0)
b=tf.Variable(0.0)
y=k*x_data+b
#二次代价函数
loss=tf.reduce_mean(tf.square(y_data-y))
#梯度下降优化器 参数为学习率
optimizer=tf.train.GradientDescentOptimizer(0.1)
train=optimizer.minimize(loss)
#初始化变量
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for _ in range(300):
        sess.run(train)
        if _%20==0:
            print(_,sess.run([k,b]))
        


0 [0.16161618, 0.31044093]
20 [0.55316633, 1.2551911]
40 [0.48048717, 1.297798]
60 [0.42193308, 1.3295784]
80 [0.3756004, 1.3547187]
100 [0.33894047, 1.3746105]
120 [0.30993396, 1.3903495]
140 [0.2869832, 1.4028027]
160 [0.2688238, 1.412656]
180 [0.25445554, 1.4204522]
200 [0.24308692, 1.426621]
220 [0.23409165, 1.4315017]
240 [0.2269744, 1.4353635]
260 [0.22134301, 1.4384192]
280 [0.2168872, 1.440837]
